licenses

diff --git a/.github/workflows/license.yml b/.github/workflows/license.yml
--- a/.github/workflows/license.yml
+++ b/.github/workflows/license.yml
@@ -18,28 +18,38 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 ---
-docker:
-  image: yegor256/rultor-image:1.23.1
-assets:
-  credentials: yegor256/home#assets/crates-credentials
-install: |
-  pdd --file=/dev/null
-merge:
-  script: |
-    cargo --color=never test -vv
-    cargo --color=never fmt --check
-    cargo doc --no-deps
-    cargo clippy
-release:
-  pre: false
-  script: |-
-    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
-    sed -i -e "s/^version = \"0.0.0\"/version = \"${tag}\"/" Cargo.toml
-    sed -i -e "s/0.0.0/${tag}/" src/lib.rs
-    cargo --color=never test --all-features -vv -- --nocapture
-    cargo --color=never test --release --all-features -vv -- --nocapture
-    cargo --color=never fmt --check
-    cargo --color=never clippy -- --no-deps
-    git commit -am "${tag}"
-    mkdir -p ~/.cargo && cp ../credentials ~/.cargo
-    cargo --color=never publish
+name: license
+'on':
+  push:
+    branches:
+      - master
+  pull_request:
+    branches:
+      - master
+jobs:
+  license:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+      - shell: bash
+        run: |
+          header="Copyright (c) 2023-$(date +%Y) Yegor Bugayenko"
+          failed="false"
+          while IFS= read -r file; do
+            if ! grep -q "${header}" "${file}"; then
+              failed="true"
+              echo "⚠️ Copyright header is not found in: ${file}"
+            else
+              echo "File looks good: ${file}"
+            fi
+          done < <(find . -type f \( \
+            -name "LICENSE.txt" -o \
+            -name "*.sh" -o \
+            -name "*.rs" -o \
+            -name "*.yml" \
+            \) \
+            -not -path './target/**' \
+            -print)
+          if [ "${failed}" = "true" ]; then
+            exit 1
+          fi
